# Generated by Django 4.2.7 on 2025-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
            ],
            options={
                'abstract': True,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementCronHealth',
            fields=[
            ],
            options={
                'db_table': 'management_cron_health',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StellarAccountSearchCache',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StellarAccountStageExecution',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StellarCreatorAccountLineage',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BigQueryPipelineConfig',
            fields=[
                ('config_id', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('bigquery_enabled', models.BooleanField(default=True)),
                ('cost_limit_usd', models.FloatField(default=0.71)),
                ('size_limit_mb', models.FloatField(default=148900.0)),
                ('pipeline_mode', models.CharField(default='BIGQUERY_WITH_API_FALLBACK', max_length=50)),
                ('instant_query_max_age_days', models.IntegerField(default=365)),
                ('api_fallback_enabled', models.BooleanField(default=True)),
                ('horizon_max_operations', models.IntegerField(default=200)),
                ('horizon_child_max_pages', models.IntegerField(default=5)),
                ('bigquery_max_children', models.IntegerField(default=100000)),
                ('bigquery_child_page_size', models.IntegerField(default=10000)),
                ('batch_processing_enabled', models.BooleanField(default=True)),
                ('batch_size', models.IntegerField(default=100)),
                ('cache_ttl_hours', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'BigQuery Pipeline Configuration',
                'verbose_name_plural': 'BigQuery Pipeline Configuration',
            },
        ),
    ]
