# Generated by Django 4.2.7 on 2025-10-14 17:17
# Local development migration for SQLite models

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        # Create StellarAccountSearchCache table
        migrations.CreateModel(
            name='StellarAccountSearchCache',
            fields=[
                ('stellar_account', models.CharField(max_length=56, primary_key=True)),
                ('network_name', models.CharField(max_length=9)),
                ('status', models.CharField(default='PENDING', max_length=127)),
                ('cached_json', models.TextField()),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apiApp_stellaraccountsearchcache',
            },
        ),

        # Create StellarCreatorAccountLineage table
        migrations.CreateModel(
            name='StellarCreatorAccountLineage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True)),
                ('stellar_account', models.CharField(max_length=56)),
                ('network_name', models.CharField(max_length=9)),
                ('stellar_creator_account', models.CharField(max_length=56)),
                ('stellar_account_created_at', models.DateTimeField(blank=True, null=True)),
                ('home_domain', models.CharField(blank=True, max_length=127)),
                ('xlm_balance', models.FloatField(default=0.0)),
                ('horizon_accounts_json', models.TextField(blank=True)),
                ('horizon_operations_json', models.TextField(blank=True)),
                ('horizon_effects_json', models.TextField(blank=True)),
                ('stellar_account_attributes_json', models.TextField(blank=True)),
                ('stellar_account_assets_json', models.TextField(blank=True)),
                ('child_accounts_json', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_hva', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=127)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apiApp_stellarcreatoraccountlineage',
            },
        ),

        # Create ManagementCronHealth table
        migrations.CreateModel(
            name='ManagementCronHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True)),
                ('created_at', models.DateTimeField()),
                ('cron_name', models.CharField(max_length=71)),
                ('status', models.CharField(default='HEALTHY', max_length=63)),
                ('reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apiApp_managementcronhealth',
                'ordering': ['-created_at'],
            },
        ),

        # Create StellarAccountStageExecution table
        migrations.CreateModel(
            name='StellarAccountStageExecution',
            fields=[
                ('stellar_account', models.CharField(max_length=56)),
                ('network_name', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField()),
                ('stage_number', models.IntegerField()),
                ('cron_name', models.CharField(max_length=127)),
                ('status', models.CharField(max_length=63)),
                ('execution_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'apiApp_stellaraccountstageexecution',
                'ordering': ['-created_at'],
            },
        ),

        # Add indexes for performance
        migrations.AddIndex(
            model_name='stellaraccountsearchcache',
            index=models.Index(fields=['network_name', 'status'], name='apiApp_stellaraccountsearchcache_network_name_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stellaraccountsearchcache',
            index=models.Index(fields=['last_fetched_at'], name='apiApp_stellaraccountsearchcache_last_fetched_at_idx'),
        ),
        migrations.AddIndex(
            model_name='stellarcreatoraccountlineage',
            index=models.Index(fields=['stellar_account', 'network_name'], name='apiApp_stellarcreatoraccountlineage_stellar_account_network_name_idx'),
        ),
        migrations.AddIndex(
            model_name='stellarcreatoraccountlineage',
            index=models.Index(fields=['stellar_creator_account'], name='apiApp_stellarcreatoraccountlineage_stellar_creator_account_idx'),
        ),
        migrations.AddIndex(
            model_name='stellarcreatoraccountlineage',
            index=models.Index(fields=['is_hva'], name='apiApp_stellarcreatoraccountlineage_is_hva_idx'),
        ),
        migrations.AddIndex(
            model_name='stellarcreatoraccountlineage',
            index=models.Index(fields=['status'], name='apiApp_stellarcreatoraccountlineage_status_idx'),
        ),
        migrations.AddIndex(
            model_name='managementcronhealth',
            index=models.Index(fields=['cron_name', '-created_at'], name='apiApp_managementcronhealth_cron_name_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='managementcronhealth',
            index=models.Index(fields=['status'], name='apiApp_managementcronhealth_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stellaraccountstageexecution',
            index=models.Index(fields=['stellar_account', 'network_name', '-created_at'], name='apiApp_stellaraccountstageexecution_stellar_account_network_name_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='stellaraccountstageexecution',
            index=models.Index(fields=['status'], name='apiApp_stellaraccountstageexecution_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stellaraccountstageexecution',
            index=models.Index(fields=['cron_name'], name='apiApp_stellaraccountstageexecution_cron_name_idx'),
        ),
    ]
