# Generated by Django 5.0.2 on 2025-10-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_auto_20251014_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='HVAStandingChange',
            fields=[
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulerConfig',
            fields=[
                ('config_id', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('scheduler_enabled', models.BooleanField(default=True, help_text="Enable/disable the background scheduler. When disabled, PENDING records won't be processed automatically.")),
                ('cron_schedule', models.CharField(default='0 */2 * * *', help_text="Cron expression for schedule (e.g., '0 */2 * * *' = every 2 hours, '*/30 * * * *' = every 30 minutes)", max_length=50)),
                ('batch_limit', models.IntegerField(default=100, help_text='Maximum number of PENDING accounts to process per scheduled run')),
                ('run_on_startup', models.BooleanField(default=True, help_text='Run the pipeline immediately when the scheduler starts (in addition to scheduled runs)')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful pipeline run', null=True)),
                ('last_run_status', models.CharField(blank=True, help_text='Status of the last run (SUCCESS, FAILED, etc.)', max_length=50)),
                ('last_run_processed', models.IntegerField(default=0, help_text='Number of accounts processed in the last run')),
                ('last_run_failed', models.IntegerField(default=0, help_text='Number of accounts that failed in the last run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Admin username who last updated', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about configuration changes')),
            ],
            options={
                'verbose_name': 'Scheduler Configuration',
                'verbose_name_plural': 'Scheduler Configuration',
                'db_table': 'scheduler_config',
            },
        ),
        migrations.AlterModelOptions(
            name='managementcronhealth',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stellaraccountsearchcache',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stellaraccountstageexecution',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='stellarcreatoraccountlineage',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='bigquerypipelineconfig',
            table='bigquery_pipeline_config',
        ),
    ]
