# Generated by Django 5.0.2 on 2025-10-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_add_scheduler_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulerconfig',
            options={'managed': True, 'verbose_name': 'Scheduler Configuration', 'verbose_name_plural': 'Scheduler Configuration'},
        ),
        migrations.AddField(
            model_name='bigquerypipelineconfig',
            name='hva_threshold_xlm',
            field=models.FloatField(default=100000.0, help_text='Minimum XLM balance to be considered a High Value Account (default: 100,000 XLM)'),
        ),
        migrations.AlterField(
            model_name='bigquerypipelineconfig',
            name='batch_size',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='schedulerconfig',
            name='batch_limit',
            field=models.IntegerField(default=6, help_text='Maximum number of PENDING accounts to process per scheduled run (slow continuous retrieval)'),
        ),
        migrations.AlterField(
            model_name='schedulerconfig',
            name='cron_schedule',
            field=models.CharField(default='*/3 * * * *', help_text="Cron expression for schedule (e.g., '*/3 * * * *' = every 3 minutes, '*/30 * * * *' = every 30 minutes)", max_length=50),
        ),
        migrations.AlterModelTable(
            name='managementcronhealth',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stellaraccountsearchcache',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stellaraccountstageexecution',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stellarcreatoraccountlineage',
            table=None,
        ),
    ]
