# Generated by Django 5.0.2 on 2025-10-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_add_hva_threshold_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigquerypipelineconfig',
            name='hva_supported_thresholds',
            field=models.TextField(default='10000,50000,100000,500000,750000,1000000', help_text='Comma-separated list of XLM thresholds for multi-threshold leaderboards (e.g., 10000,50000,100000,500000,750000,1000000). Each threshold creates a separate leaderboard.'),
        ),
    ]
