# Generated by Django 5.0.2 on 2025-10-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_add_dual_pipeline_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRateLimiterConfig',
            fields=[
                ('config_id', models.CharField(default='default', max_length=50, primary_key=True, serialize=False)),
                ('horizon_percentage', models.IntegerField(default=100, help_text='Horizon API rate limit as percentage of max (100% = 120 req/min). Example: 85% = 102 req/min')),
                ('stellar_expert_percentage', models.IntegerField(default=83, help_text='Stellar Expert API rate limit as percentage of max (100% = 50 req/min). Example: 85% = 42 req/min')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Admin username who last updated', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about configuration changes')),
            ],
            options={
                'verbose_name': 'API Rate Limiter Configuration',
                'verbose_name_plural': 'API Rate Limiter Configuration',
                'db_table': 'api_rate_limiter_config',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='bigquerypipelineconfig',
            name='api_pipeline_batch_size',
            field=models.IntegerField(default=3, help_text='Number of accounts to process per API pipeline run (default: 3 for slow continuous retrieval)'),
        ),
        migrations.AddField(
            model_name='bigquerypipelineconfig',
            name='api_pipeline_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable the API-only pipeline for consistent PENDING record processing'),
        ),
        migrations.AddField(
            model_name='bigquerypipelineconfig',
            name='api_pipeline_interval_seconds',
            field=models.IntegerField(default=120, help_text='Time between API pipeline runs in seconds (default: 120 = 2 minutes)'),
        ),
    ]
