# Generated by Django 5.0.2 on 2025-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_add_api_rate_limiter_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigquerypipelineconfig',
            name='bigquery_pipeline_interval_seconds',
            field=models.IntegerField(default=300, help_text='Time between BigQuery pipeline runs in seconds (default: 300 = 5 minutes)'),
        ),
        migrations.AlterField(
            model_name='bigquerypipelineconfig',
            name='api_pipeline_batch_size',
            field=models.IntegerField(default=9, help_text='Number of accounts to process per API pipeline run (default: 9 for continuous retrieval)'),
        ),
        migrations.AlterField(
            model_name='bigquerypipelineconfig',
            name='api_pipeline_interval_seconds',
            field=models.IntegerField(default=180, help_text='Time between API pipeline runs in seconds (default: 180 = 3 minutes)'),
        ),
        migrations.AlterField(
            model_name='schedulerconfig',
            name='batch_limit',
            field=models.IntegerField(default=9, help_text='Maximum number of PENDING accounts to process per scheduled run (slow continuous retrieval)'),
        ),
    ]
