# Generated by Django 5.0.2 on 2025-10-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_add_pipeline_intervals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchedulerConfig',
        ),
    ]
