"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-4ju2n@$f9d0c=h)_g0lbb%k9&@rf(xa$d$g$&5ri$uf)*gev^4'
SECRET_KEY = config('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Environment setting for database selection
ENV = config('ENV', default='development')

# NAS / self-host: keep always-on footprint small (see docs/StellarMapWeb)
# LIGHT_MODE=1 → lean cache, quieter logs, longer UI poll TTL defaults
_light_raw = str(config('LIGHT_MODE', default='0')).strip().lower()
LIGHT_MODE = _light_raw in ('1', 'true', 'yes', 'on')

# Hosts: merge .env ALLOWED_HOSTS with localhost + optional Replit domains
_allowed_from_env = [
    s.strip() for s in config('ALLOWED_HOSTS', default='').split(',') if s.strip()
]
ALLOWED_HOSTS = list(dict.fromkeys(
    ['127.0.0.1', 'localhost', '0.0.0.0']
    + _allowed_from_env
    + ([d for d in os.environ.get("REPLIT_DOMAINS", "").split(',') if d])
))
# Django does not treat literal "*" as "all hosts"; expand for lab HTTP binding
if '*' in ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://" + domain for domain in os.environ.get("REPLIT_DOMAINS", "").split(',') if os.environ.get("REPLIT_DOMAINS")
]

# Application definition

# Cassandra Configuration
CASSANDRA_KEYSPACE = config('CASSANDRA_KEYSPACE', default='stellarmapweb')
ASTRA_DB_TOKEN = config('ASTRA_DB_TOKEN', default='').strip()
# Lab: read Astra without ENV=production (no cron/writes). Requires ASTRA_DB_TOKEN.
_cassandra_ro_raw = str(config('CASSANDRA_READ_ONLY', default='0')).strip().lower()
CASSANDRA_READ_ONLY = _cassandra_ro_raw in ('1', 'true', 'yes', 'on') and bool(ASTRA_DB_TOKEN)
# Use Cassandra models + routing for apiApp when production OR lab RO mode
USE_CASSANDRA = (ENV in ['production', 'replit']) or CASSANDRA_READ_ONLY
# CASSANDRA_FALLBACK_ORDER_BY_PYTHON = True  # Disabled - causes TypeError with None value comparisons

# Path to secure connect bundle
SECURE_CONNECT_BUNDLE_PATH = BASE_DIR.parent / 'secure-connect-stellarmapwebastradb.zip'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apiApp',
    'radialTidyTreeApp',
    'webApp',
]

# Conditionally add Cassandra support if ASTRA_DB_TOKEN is provided
if ASTRA_DB_TOKEN:
    INSTALLED_APPS.insert(0, 'django_cassandra_engine')  # Must be first for Cassandra support
# Expose for helpers that only import settings
os.environ.setdefault('CASSANDRA_READ_ONLY', '1' if CASSANDRA_READ_ONLY else '0')
os.environ.setdefault('USE_CASSANDRA', '1' if USE_CASSANDRA else '0')

# Database: SQLite (default lab file) OR Postgres via DATABASE_URL / DATABASE_DRIVER=pg
# Shared NAS Postgres example: postgres://stellarmap:***@127.0.0.1:5433/StellarMapDB
_db_driver = str(config('DATABASE_DRIVER', default='sqlite')).strip().lower()
_database_url = config('DATABASE_URL', default='').strip()
if _db_driver in ('pg', 'postgres', 'postgresql') or (
    _database_url.startswith('postgres') and _db_driver != 'sqlite'
):
    # Prefer DATABASE_URL (same pattern as ChronoTrace / DoqumentWeb)
    try:
        import urllib.parse as _urlparse

        _u = _urlparse.urlparse(_database_url)
        if not _u.scheme.startswith('postgres'):
            raise ValueError('DATABASE_URL must be a postgres:// URL')
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': _urlparse.unquote(_u.path.lstrip('/') or 'StellarMapDB'),
                'USER': _urlparse.unquote(_u.username or ''),
                'PASSWORD': _urlparse.unquote(_u.password or ''),
                'HOST': _u.hostname or '127.0.0.1',
                'PORT': str(_u.port or 5432),
                'CONN_MAX_AGE': int(config('PG_CONN_MAX_AGE', default=60)),
                'OPTIONS': {
                    'connect_timeout': int(config('PG_CONNECT_TIMEOUT', default=10)),
                },
            }
        }
    except Exception:
        # Fallback discrete vars
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': config('POSTGRES_DB', default='StellarMapDB'),
                'USER': config('POSTGRES_USER', default='stellarmap'),
                'PASSWORD': config('POSTGRES_PASSWORD', default=''),
                'HOST': config('POSTGRES_HOST', default='127.0.0.1'),
                'PORT': config('POSTGRES_HOST_PORT', default=config('POSTGRES_PORT', default='5433')),
                'CONN_MAX_AGE': int(config('PG_CONN_MAX_AGE', default=60)),
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # NAS: WAL + timeout reduce lock wait CPU spin under concurrent reads
            'OPTIONS': {
                'timeout': 20,
            },
        }
    }

# Conditionally add Cassandra database if ASTRA_DB_TOKEN is provided
if ASTRA_DB_TOKEN:
    DATABASES['cassandra'] = {
        'ENGINE': 'django_cassandra_engine',
        'NAME': CASSANDRA_KEYSPACE,
        'USER': 'token',  # Literal string 'token' for Astra DB
        'PASSWORD': ASTRA_DB_TOKEN,  # Your Astra token
        'OPTIONS': {
            'connection': {
                'cloud': {
                    'secure_connect_bundle': str(SECURE_CONNECT_BUNDLE_PATH)
                },
                'retry_connect': True,
                'protocol_version': 4,
            }
        }
    }

# Database routing:
# - production / replit → Cassandra (read+write when token allows)
# - CASSANDRA_READ_ONLY=1 + token → Cassandra for apiApp reads (writes blocked in router)
# - else development → default (SQLite / Postgres)
if USE_CASSANDRA and ASTRA_DB_TOKEN:
    DATABASE_APPS_MAPPING = {
        'apiApp': 'cassandra',
    }
else:
    DATABASE_APPS_MAPPING = {
        'apiApp': 'default',
    }

# Enable the database router
DATABASE_ROUTERS = ['StellarMapWeb.router.DatabaseAppsRouter']

# Cache: locmem is lighter than DatabaseCache on SQLite (no extra table churn).
# LIGHT_MODE keeps the process small for always-on NAS; full mode allows larger sets.
if LIGHT_MODE:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'stellarmap-light',
            'OPTIONS': {
                'MAX_ENTRIES': int(config('CACHE_MAX_ENTRIES', default=256)),
            },
            'TIMEOUT': int(config('CACHE_TIMEOUT', default=120)),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'stellarmap_cache_table',
            'OPTIONS': {
                'MAX_ENTRIES': int(config('CACHE_MAX_ENTRIES', default=10000)),
                'CULL_FREQUENCY': 4,
            }
        }
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Managers: Tailscale QR session required for /admin/ + management APIs.
    # Search / dashboard / read APIs stay public.
    'StellarMapWeb.middleware.ManagerGateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- Manager auth (Tailscale QR) — same idea as ChronoTrace / DoqumentWeb ---
# Public visitors: search + read-only without login.
# Managers: AUTH_MODE=tailscale-qr + TAILSCALE_ALLOW_LOGINS email allowlist.
AUTH_MODE = config('AUTH_MODE', default='tailscale-qr')
TAILSCALE_ALLOW_LOGINS = config('TAILSCALE_ALLOW_LOGINS', default='')
TAILSCALE_SOCKET = config(
    'TAILSCALE_SOCKET',
    default='/volume6/@appdata/Tailscale/tailscaled.sock',
)
TAILSCALE_QR_TTL_MS = config('TAILSCALE_QR_TTL_MS', default=90000, cast=int)
PUBLIC_BASE_URL = config('PUBLIC_BASE_URL', default='')
SESSION_IDLE_HOURS = config('SESSION_IDLE_HOURS', default=8, cast=int)
# Cookie flags for lab HTTP (override for HTTPS prod)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_NAME = config('SESSION_COOKIE_NAME', default='stellarmap.sid')
# JS login QR needs to read csrftoken cookie
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_NAME = 'csrftoken'

# Export auth settings for helpers that read os.environ
os.environ.setdefault('AUTH_MODE', str(AUTH_MODE))
if TAILSCALE_ALLOW_LOGINS:
    os.environ.setdefault('TAILSCALE_ALLOW_LOGINS', str(TAILSCALE_ALLOW_LOGINS))
os.environ.setdefault('TAILSCALE_SOCKET', str(TAILSCALE_SOCKET))
os.environ.setdefault('TAILSCALE_QR_TTL_MS', str(TAILSCALE_QR_TTL_MS))

# Serve static files from the app process (gunicorn/host) without a separate nginx.
# WhiteNoise is already a dependency; default on for lab/LIGHT_MODE.
_use_whitenoise = str(
    config('USE_WHITENOISE', default='1' if (LIGHT_MODE or ENV == 'development') else '0')
).lower() in ('1', 'true', 'yes', 'on')
if _use_whitenoise:
    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')
    # Find app static without full collectstatic (saves disk/CPU on NAS first boot)
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = DEBUG
    WHITENOISE_MAX_AGE = 60 if DEBUG else 3600

# Only use clickjacking protection in deployments because the Development Web View uses
# iframes and needs to be a cross origin.
if ("REPLIT_DEPLOYMENT" in os.environ):
    MIDDLEWARE.append('django.middleware.clickjacking.XFrameOptionsMiddleware')

ROOT_URLCONF = 'StellarMapWeb.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / 'templates'],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
            'StellarMapWeb.context_processors.nas_runtime',
        ]
    }
}]

WSGI_APPLICATION = 'StellarMapWeb.wsgi.application'

# REST_FRAMEWORK configuration removed since rest_framework is not installed

import logging

# Logging: LIGHT_MODE / non-DEBUG keeps console quiet (less I/O and disk log growth)
_root_level = config(
    'DJANGO_LOG_LEVEL',
    default=('WARNING' if LIGHT_MODE else ('DEBUG' if DEBUG else 'INFO')),
)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': _root_level,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING' if LIGHT_MODE else _root_level,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'WARNING' if LIGHT_MODE else 'INFO',
            'propagate': False,
        },
        # Reduce Cassandra driver verbosity to prevent flooding stderr
        'cassandra': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
        'cassandra.cluster': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
        'cassandra.connection': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
        'cassandra.cqlengine.connection': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
        'cassandra.pool': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
        'cassandra.io.libevreactor': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
        'cassandra.protocol_features': {
            'handlers': ['console'],
            'level': 'ERROR' if LIGHT_MODE else 'WARNING',
            'propagate': False,
        },
    },
}

# UI / API poll cadence (ms) — dashboard / general background
# LIGHT_MODE defaults to 60s to cut background request load on NAS
POLL_INTERVAL_MS = int(
    config('POLL_INTERVAL_MS', default='60000' if LIGHT_MODE else '30000')
)
# Pending-accounts API list cap (RAM + JSON size)
PENDING_ACCOUNTS_LIMIT = int(
    config('PENDING_ACCOUNTS_LIMIT', default='50' if LIGHT_MODE else '100')
)

# Near-real-time (interest-driven SDK worker + faster search poll). Default off.
# Requires write-capable DB (CASSANDRA_READ_ONLY must be 0 for queueing).
_near_rt_raw = str(config('NEAR_RT_ENABLED', default='0')).strip().lower()
NEAR_RT_ENABLED = _near_rt_raw in ('1', 'true', 'yes', 'on')
# Search-page lineage poll only (dashboard keeps POLL_INTERVAL_MS)
NEAR_RT_SEARCH_POLL_MS = int(
    config(
        'NEAR_RT_SEARCH_POLL_MS',
        default='30000' if NEAR_RT_ENABLED else str(POLL_INTERVAL_MS),
    )
)
# SDK worker loop (management command run_sdk_near_rt_worker)
NEAR_RT_WORKER_INTERVAL_SEC = int(config('NEAR_RT_WORKER_INTERVAL_SEC', default='45'))
NEAR_RT_WORKER_LIMIT = int(config('NEAR_RT_WORKER_LIMIT', default='5'))
NEAR_RT_WORKER_CONCURRENT = int(config('NEAR_RT_WORKER_CONCURRENT', default='3'))
NEAR_RT_WORKER_NETWORK = str(config('NEAR_RT_WORKER_NETWORK', default='public')).strip() or 'public'

# Lineage aggregation flags (see docs/StellarMapWeb/design-lineage-aggregation.md)
# When 1: pipelines + parent-lineage cron write full projection JSON via
# LineageAggregateService.rebuild_and_cache (DB-only). Default off for safe rollout.
_lineage_write_raw = str(
    config('LINEAGE_WRITE_PROJECTION', default='0')
).strip().lower()
LINEAGE_WRITE_PROJECTION = _lineage_write_raw in ('1', 'true', 'yes', 'on')

# When 1: search_view serves table+tree from LineageAggregateService (one projection).
_lineage_ssr_raw = str(
    config('LINEAGE_UNIFIED_AGGREGATE', default='0')
).strip().lower()
LINEAGE_UNIFIED_AGGREGATE = _lineage_ssr_raw in ('1', 'true', 'yes', 'on')

# When 1: SSR projection includes sibling nodes (larger payload). Default off for NAS.
_lineage_ssr_sib_raw = str(
    config('LINEAGE_SSR_INCLUDE_SIBLINGS', default='0')
).strip().lower()
LINEAGE_SSR_INCLUDE_SIBLINGS = _lineage_ssr_sib_raw in ('1', 'true', 'yes', 'on')

# Process-local TTL/LRU for lineage API JSON (default on; isolates from LocMem).
_lineage_api_cache_raw = str(
    config('LINEAGE_API_RESPONSE_CACHE', default='1')
).strip().lower()
LINEAGE_API_RESPONSE_CACHE = _lineage_api_cache_raw in ('1', 'true', 'yes', 'on')

# When 1: search UI fetches path/structure first, then siblings in a second request.
# Default on when NEAR_RT_ENABLED (faster first paint while worker fills data).
_lineage_prog_raw = str(
    config(
        'LINEAGE_PROGRESSIVE_SIBLINGS',
        default='1' if NEAR_RT_ENABLED else '0',
    )
).strip().lower()
LINEAGE_PROGRESSIVE_SIBLINGS = _lineage_prog_raw in ('1', 'true', 'yes', 'on')

# High Value Accounts page (bounded Cassandra scan + short cache)
HVA_DISPLAY_LIMIT = int(config('HVA_DISPLAY_LIMIT', default='100'))
HVA_CACHE_TTL_SEC = int(config('HVA_CACHE_TTL_SEC', default='120'))
HVA_CASSANDRA_MAX_SCAN = int(config('HVA_CASSANDRA_MAX_SCAN', default='2500'))
# 0 on Cassandra RO by default (avoid N partition reads); SQL can enrich lightly
_hva_enrich_default = '0' if CASSANDRA_READ_ONLY or (ENV in ['production', 'replit']) else '20'
HVA_RANK_ENRICH_LIMIT = int(config('HVA_RANK_ENRICH_LIMIT', default=_hva_enrich_default))

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR.parent / 'static'
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SQLite PRAGMA helpers (applied once per connection)
from django.db.backends.signals import connection_created  # noqa: E402


def _sqlite_pragma(sender, connection, **kwargs):
    if connection.vendor != 'sqlite':
        return
    with connection.cursor() as cursor:
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA synchronous=NORMAL;')
        cursor.execute('PRAGMA temp_store=MEMORY;')
        # Smaller mmap/cache in LIGHT_MODE for NAS / old laptop RAM
        if LIGHT_MODE:
            cursor.execute('PRAGMA mmap_size=16777216;')   # 16 MiB
            cursor.execute('PRAGMA cache_size=-4000;')     # ~4 MiB page cache
        else:
            cursor.execute('PRAGMA mmap_size=67108864;')   # 64 MiB
            cursor.execute('PRAGMA cache_size=-16000;')


connection_created.connect(_sqlite_pragma)
